version: '3.9'

services:
  db:
    image: postgres:17.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mindfactory
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: .
    environment:
      DB_HOST: db    
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: mindfactory
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  db_data:
